#!/usr/bin/env bash
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Get current location
DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

log() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

error() {
  echo -e "${RED}[ERROR]${NC} $1"
  exit 1
}

check_dependencies() {
  command -v brew >/dev/null 2>&1 || error "Homebrew is required but not installed. https://brew.sh/"
  command -v git >/dev/null 2>&1 || error "Git is required but not installed. https://git-scm.com/downloads"
}

safe_link() {
  local src="$1"
  local dest="$2"

  if [ -e "$dest" ] || [ -L "$dest" ]; then
      log "Found $dest - removing..."
      rm -f "$dest"
  fi

  if [ ! -e "$src" ]; then
      error "Source file $src does not exist!"
  fi

  log "Linking $dest to $src"
  ln -s "$src" "$dest"
}

install_oh_my_zsh() {
  if [ -d "$HOME/.oh-my-zsh" ]; then
      log "oh-my-zsh is already installed."
  else
      log "Installing oh-my-zsh..."
      if ! sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; then
          error "Failed to install Deno"
      fi
  fi
}

install_deno() {
  if [ -d "$HOME/.deno/bin/deno" ]; then
    log "deno is already installed.."
  else
    log "Installing Deno"
    if ! sh -c "$(curl -fsSL https://deno.land/install.sh)"; then
      error "Failed to install oh-my-zsh"
    fi
  fi
}

setup_git() {
  safe_link "$DIR/git/.gitconfig" "$HOME/.gitconfig"
}

setup_zsh() {
  safe_link "$DIR/zsh/.zshrc" "$HOME/.zshrc"
  safe_link "$DIR/zsh/dracula.zsh-theme" "$HOME/.oh-my-zsh/themes/dracula.zsh-theme"
  safe_link "$DIR/zsh/aliases.zsh" "$HOME/.oh-my-zsh/custom/aliases.zsh"
}

setup_npm() {
  safe_link "$DIR/.npmrc" "$HOME/.npmrc"
}

setup_brew() {
  safe_link "$DIR/Brewfile" "$HOME/Brewfile"
  log "Executing brew bundle install..."
  if ! brew bundle install; then
      error "Brew bundle install failed"
  fi
}

setup_duti() {
  safe_link "$DIR/extras/duti_picview.config" "$HOME/duti_picview.config"
}

main() {
  log "Starting installation from $DIR..."

  check_dependencies

  install_oh_my_zsh
  install_deno

  setup_git
  setup_zsh
  setup_npm
  setup_brew
  setup_duti

  log "Installation completed successfully! 🎉"
}

main "$@"
